<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Freethrow</Product>
    <Authors>Freethrow contributors</Authors>
    <Copyright>Copyright (C) 2026 Freethrow contributors</Copyright>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/kramav/Freethrow</RepositoryUrl>
  </PropertyGroup>

</Project>
